language: python
python:
    - "3.4"
    - "3.5"
    - "3.6"
    - "3.7"
before_install:
    - python --version
    - pip install -U pip
    - pip install -U pytest
    - pip install codecov
install:
    - pip install ".[test]" .
before_script:
    - "curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install.sh | sudo bash"
script:
    - pytest
    - fossa init
    - fossa analyze
after_success:
    - codecov
